# alembic.ini
# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# migration file section of the filename.
# revision_file_token =

# set to 'true' to remember revisions
# truncate_slug_length = 40

# set to 'true' to have dates in filenames
# revision_file_token =

# set to 'true' to have sequential number in filenames
# revision_file_token =

# 'revision_environment' is a zero-argument callable
# returning a <class>RevisionEnvironment, and is used
# to access the MigrationContext. It should be loaded
# from a module.
# revision_environment =

# 'sourceless' is a zero-argument callable returning True
# or False. When True, the revision environment will not
# attempt to load the source file corresponding to the
# revision.
# sourceless = false

# prepend_sys_path = .

# version_path_separator = :

# set to 'true' to search for version locations
# in the version_path_separator delimited list
# of directories.
# search_path =

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

# sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail and examples

# keys are script names, values are functions
# update_module_prefix = %(here)s.update_module_prefix
# update_versioned_links = %(here)s.update_versioned_links

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARN" logs neither.  (Recommended for production)

[logger_alembic]
level = INFO
handlers =
qualname = alembic